### ISSUE TITLE
Output for second round is incorrect

### ISSUE THREAD

**Issue by milchy07** [matthew-agard/2021-March-Madness-Predictions#1]
In March_Madness_Predictions.ipynb, all the way at the bottom in Pre-tournament model evaluation, some game outcomes are marked as upsets when in reality the underdog and favorite have switched columns and are being confused for each other. This might affect the end outcome of your model (i.e. Alabama winning it all)

**Comment by matthew-agard** [comment]
Hi @milchy07, thanks for pointing that out. I went over the code and it appears that the teams being chosen to advance are correct based on the model's learned trends, but like you said the underdogs and favorites are getting mixed up on a few matchups. I'm still looking into it and hope to have it resolved in the near future. Enjoy the tournament!

**Comment by milchy07** [comment]
Thanks for the quick response! It's a really cool model and takes into consideration some important parameters.

**Comment by matthew-agard** [comment]
No problem on the quick response, and thanks! I'm hoping to build a better model for next year, feel free to star and/or fork the repo to keep up with it and possibly propose any interesting ideas.
